// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: beango_town_contract.proto
// </auto-generated>
// Original file comments:
// This files is part of the Hello World smart contract example that is included in Boilerplate.
// It is only the definition of the contract, implementation is located in the "contract" folder
// and tests are located in the "test" folder.
//
// You can use this as a basic template for new contracts.
// 
// When building Boilerplate or the contract project located in the "../contract/AElf.Contracts.BeangoTownContract/" 
// protoc (the protobuf compiler) will be invoked and this file will produce a .c.cs file and .g.cs file, in the 
// "../contract/AElf.Contracts.BeangoTownContract/Protobuf/Generated/" folder. 
//
// the version of the language, use proto3 for contracts
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace Contracts.BeangoTownContract {

  #region Events
  public partial class Played : aelf::IEvent<Played>
  {
    public global::System.Collections.Generic.IEnumerable<Played> GetIndexed()
    {
      return new List<Played>
      {
      };
    }

    public Played GetNonIndexed()
    {
      return new Played
      {
        PlayBlockHeight = PlayBlockHeight,
        PlayId = PlayId,
        PlayerAddress = PlayerAddress,
      };
    }
  }

  public partial class Bingoed : aelf::IEvent<Bingoed>
  {
    public global::System.Collections.Generic.IEnumerable<Bingoed> GetIndexed()
    {
      return new List<Bingoed>
      {
      };
    }

    public Bingoed GetNonIndexed()
    {
      return new Bingoed
      {
        PlayBlockHeight = PlayBlockHeight,
        GridType = GridType,
        GridNum = GridNum,
        Score = Score,
        IsComplete = IsComplete,
        PlayId = PlayId,
        BingoBlockHeight = BingoBlockHeight,
        PlayerAddress = PlayerAddress,
      };
    }
  }

  #endregion
  /// <summary>
  /// the contract definition: a gRPC service definition.
  /// </summary>
  public static partial class BeangoTownContractContainer
  {
    static readonly string __ServiceName = "BeangoTownContract";

    #region Marshallers
    static readonly aelf::Marshaller<global::Contracts.BeangoTownContract.PlayInput> __Marshaller_PlayInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Contracts.BeangoTownContract.PlayInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Contracts.BeangoTownContract.PlayOutput> __Marshaller_PlayOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Contracts.BeangoTownContract.PlayOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Hash> __Marshaller_aelf_Hash = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Hash.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Contracts.BeangoTownContract.GameLimitSettings> __Marshaller_GameLimitSettings = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Contracts.BeangoTownContract.GameLimitSettings.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Address> __Marshaller_aelf_Address = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Address.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.BoolValue> __Marshaller_google_protobuf_BoolValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.BoolValue.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Contracts.BeangoTownContract.PlayerInformation> __Marshaller_PlayerInformation = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Contracts.BeangoTownContract.PlayerInformation.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Contracts.BeangoTownContract.GetBoutInformationInput> __Marshaller_GetBoutInformationInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Contracts.BeangoTownContract.GetBoutInformationInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Contracts.BeangoTownContract.BoutInformation> __Marshaller_BoutInformation = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Contracts.BeangoTownContract.BoutInformation.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::Contracts.BeangoTownContract.PlayInput, global::Contracts.BeangoTownContract.PlayOutput> __Method_Play = new aelf::Method<global::Contracts.BeangoTownContract.PlayInput, global::Contracts.BeangoTownContract.PlayOutput>(
        aelf::MethodType.Action,
        __ServiceName,
        "Play",
        __Marshaller_PlayInput,
        __Marshaller_PlayOutput);

    static readonly aelf::Method<global::AElf.Types.Hash, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Bingo = new aelf::Method<global::AElf.Types.Hash, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Bingo",
        __Marshaller_aelf_Hash,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Contracts.BeangoTownContract.GameLimitSettings, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetGameLimitSettings = new aelf::Method<global::Contracts.BeangoTownContract.GameLimitSettings, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetGameLimitSettings",
        __Marshaller_GameLimitSettings,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Initialize = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Initialize",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ChangeAdmin = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ChangeAdmin",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_CheckBeanPass = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.View,
        __ServiceName,
        "CheckBeanPass",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_BoolValue);

    static readonly aelf::Method<global::AElf.Types.Address, global::Contracts.BeangoTownContract.PlayerInformation> __Method_GetPlayerInformation = new aelf::Method<global::AElf.Types.Address, global::Contracts.BeangoTownContract.PlayerInformation>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPlayerInformation",
        __Marshaller_aelf_Address,
        __Marshaller_PlayerInformation);

    static readonly aelf::Method<global::Contracts.BeangoTownContract.GetBoutInformationInput, global::Contracts.BeangoTownContract.BoutInformation> __Method_GetBoutInformation = new aelf::Method<global::Contracts.BeangoTownContract.GetBoutInformationInput, global::Contracts.BeangoTownContract.BoutInformation>(
        aelf::MethodType.View,
        __ServiceName,
        "GetBoutInformation",
        __Marshaller_GetBoutInformationInput,
        __Marshaller_BoutInformation);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetAdmin = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAdmin",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Contracts.BeangoTownContract.GameLimitSettings> __Method_GetGameLimitSettings = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Contracts.BeangoTownContract.GameLimitSettings>(
        aelf::MethodType.View,
        __ServiceName,
        "GetGameLimitSettings",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_GameLimitSettings);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Contracts.BeangoTownContract.BeangoTownContractReflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::AElf.Standards.ACS12.Acs12Reflection.Descriptor.Services[0],
          global::Contracts.BeangoTownContract.BeangoTownContractReflection.Descriptor.Services[0],
        };
      }
    }
    #endregion

    /// <summary>Base class for the contract of BeangoTownContract</summary>
   

  }
}
#endregion

